name: CI
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    container: 'nvidia/cuda:12.8.0-devel-ubuntu22.04'
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
